name: switchable_padding
description: A widget that adds calculated padding to the child according to the given width.
version: 1.0.0
homepage: https://github.com/koji-1009/switchable_padding

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
